version: '3'
services:
  aws:
    image: manojraut8695/trainaws:latest
    ports:
      - "8000:80"
    deploy:
      replicas: 3

  devops:
    image: manojraut8695/traindevops:latest
    ports:
      - "8001:80"
    deploy:
      replicas: 3

  azure:
    image: manojraut8695/trainazure:latest
    ports:
      - "8002:80"
    deploy:
      replicas: 3

  datascience:
    image: manojraut8695/traindatascience:latest
    ports:
      - "8003:80"
    deploy:
      replicas: 3
